Update the version of XED to 2015-09-10 for 64 and 32-bit x86, but not yet for k1om (KNC Phi).  There are still some issues left to work out for Phi.
Although this XED is two years later than our previous one, I have yet
to find a binary where fnbounds produces a different answer.

Trunk will auto-config and build with either old or new XED, but
toolkit branches (before merging with trunk) will not build with the
new XED.  In that case, use externals tag 'pre-xed-2015', or one rev
before this one.

diff --git a/xed2/install b/xed2/install
--- a/xed2/install
+++ b/xed2/install
@@ -11,23 +11,27 @@ PKG_NAME=xed2
 pre_install
 prefix="$xed2_prefix"
 
-if test "$use_xed2_k1om" = yes ; then
-    XED2=extras/xed2-mic
-elif test "$use_xed2_mic" = yes ; then
-    XED2=xed-install-knc-2013-05-31-lin-x86-64
-elif test "$wordsize" = 32 ; then
-    XED2=extras/xed2-ia32
-else
-    XED2=extras/xed2-intel64
-fi
-
 mkdir -p "$prefix" || die "unable to mkdir: $prefix"
 
-cd "$XED2" || die "unable to cd: $XED2"
-test -d lib || die "missing lib directory: $XED2"
+# In case of multiple xed directories (x86-64), we take one include
+# subdir and all lib subdirs.
 
-echo "copying files from $XED2"
-tar cf - include lib | ( cd "$prefix" && tar xvf - )
-test $? -eq 0 || die "tar copy failed"
+include_done=no
+for dir in extras/xed2-* kits/xed-*
+do
+    cd "$ORIG_PKG_DIR" || die "unable to cd: $ORIG_PKG_DIR"
+    if test -d "$dir" ; then
+	echo "copying files from $dir ..."
+	cd "$dir" || die "unable to cd: $dir"
+	if test "$include_done" = no ; then
+	    tar cf - include | ( cd "$prefix" && tar xvf - )
+	    include_done=yes
+	fi
+	tar cf - lib | ( cd "$prefix" && tar xvf - )
+    fi
+done
+
+# Some libxed.so files are missing world execute permission (yuck).
+chmod -f a+x ${prefix}/lib/lib*.so
 
 post_install
