Update the binutils config scripts for version 2.27 and remove the option of building the old, patched 2.20.1 version.  Add the mk-bin-lite.sh script for making a reduced tar file with only the components that we use for hpctoolkit (for space).
This is the first step in the final push to merge back to trunk and
contains everything for binutils except the tar file.

diff --git a/binutils/post-install-27 b/binutils/post-install-27
--- a/binutils/post-install-27
+++ b/binutils/post-install-27
@@ -2,25 +2,25 @@
 #
 #  Binutils post-install
 #
-#  Install extra headers and libiberty.
+#  Install extra headers and libraries.
 #
 #  $Id$
 #
 
 PKG_NAME=binutils
-src=version-binutils-2.20.1/binutils-2.20.1
+src=binutils-2.27
 
 . ../build-utils/configure.inc
 prefix="$binutils_prefix"
 
 #
-# Install extra headers: demangle.h and its dependencies.
+# Install headers: demangle.h and its dependencies.
 #
 headers='ansidecl.h demangle.h libiberty.h'
 src_dir="${src}/include"
 dest_dir="${prefix}/include"
 
-echo "install extra headers: $headers"
+echo "install headers: $headers"
 mkdir -p "$dest_dir" || die "unable to mkdir: $dest_dir"
 for file in $headers
 do
@@ -28,9 +28,9 @@ do
 done
 
 #
-# Libiberty doesn't obey --libdir and always installs into a multilib
-# directory (lib64 or lib32).  Instead of hacking their Makefile, we
-# just copy any library in lib64 or lib32 to lib.
+# Some libraries don't obey --libdir= and always install into a
+# multilib directory (lib64, lib32).  Instead of hacking their
+# Makefile, we just copy any library from lib64 or lib32 to lib.
 #
 cd "$prefix" || die "unable to cd: $prefix"
 mkdir -p lib || die "unable to mkdir: lib"
@@ -41,3 +41,13 @@ do
 	cp -f "$file" lib || die "unable to copy: $file"
     fi
 done
+
+#
+# Sometimes, libiberty is not installed at all, so copy it from the
+# work directory.
+#
+file=libiberty.a
+if test ! -f "lib/$file" ; then
+    echo "copy $file to lib"
+    cp -f "${ORIG_PKG_DIR}/work/libiberty/$file" lib || die "unable to copy: $file"
+fi
