Add cotire-patch to disable cotire on k1om.  This was breaking the build on k1om due to including inttypes.h before Types.h.
Add -DBOOST_NO_CXX11_CONSTEXPR to CXXFLAGS on k1om.  This was also
breaking the build on k1om due to boost misidentifying features in
the g++ k1om compiler.

diff --git a/symtabAPI/post-fetch b/symtabAPI/post-fetch
--- a/symtabAPI/post-fetch
+++ b/symtabAPI/post-fetch
@@ -4,12 +4,15 @@
 #  whitespace.  Dyninst changed the indentation in Object-elf.C, so
 #  the loose whitespace (-l) allows the patch to apply both before and
 #  after the change.
+#
+#  Also, apply cotire-patch only on k1om.
 # 
 
 PKG_NAME=symtabAPI
 src=dyninst
 
 patch_file=patches/k1om-patch
+cotire_file=patches/cotire-patch
 
 . ../build-utils/configure.inc
 
@@ -19,6 +22,16 @@ case "$host" in
 	    echo `basename $patch_file`
 	    patch -d "$src" -p1 -l < "$patch_file" \
 		|| die "patch failed: $patch_file"
+	fi
+	;;
+esac
+
+case "$host" in
+    *k1om* )
+	if test -f "$cotire_file" ; then
+	    echo `basename $cotire_file`
+	    patch -d "$src" -p1 < "$cotire_file" \
+		|| die "patch failed: $cotire_file"
 	fi
 	;;
 esac
