First support for building boost libraries for dyninst within externals.  This much covers the easy cases.
Not yet supported: 32-bit or k1om.

diff --git a/boost/install b/boost/install
--- a/boost/install
+++ b/boost/install
@@ -12,12 +12,18 @@ src=boost_1_59_0
 pre_install
 prefix="$boost_prefix"
 include="$prefix/include"
+stage="${ORIG_PKG_DIR}/work"
 
 mkdir -p "$include" || die "unable to mkdir: $include"
 
-echo "copying boost files (quietly) ..."
+echo "copying boost include files (quietly) ..."
 cd "$src" || die "unable to cd: $src"
 tar cf - boost | ( cd "$include" && tar xf - )
+test $? -eq 0 || die "tar copy failed"
+
+echo "copying boost library files ..."
+cd "$stage" || die "unable to cd: $stage"
+tar cf - lib | ( cd "$prefix" && tar xvf - )
 test $? -eq 0 || die "tar copy failed"
 
 post_install
